site_name: Autobot Technical E-Manual
nav:
    - Mini :
        - 'วิธีปรับตำแหน่ง Sensor กันตก' : mini_sensor_adj.md
        - 'วิธีถอดเปลี่ยนล้อหน้า' : mini_front_wheel_adj.md
        - 'วิธีถอดเปลี่ยนชุดล้อซ้ายและขวา' : mini_drive_wheel.md
        - 'วิธีเปลี่ยนแบตเตอรี่' : mini_battery.md
    - Lazer 1:
        - 'วิธีรีเซ็ทการตั้งค่าและกลับไปใช้ค่าโรงงาน(Factory Reset)' : lazer1_factory_rst.md
    - Lazer 4: 
        - 'วิธีเชื่อมต่อ Lazer 4 เพื่อสั่งงานผ่านโทรศัพท์มือถือ' : lazer4_app_con.md
        - 'วิธีสร้างและเพิ่ม Map ของหุ่นยนต์ Lazer 4' : lazer4_mapping.md
        - 'วิธีกั้นพื้นที่ (Virtual Wall)' : lazer4_virtual_wall.md
    - Dibea F20Max/Dibea F20Plus:
        - 'วิธีถอดแปรง Dibea F20Max/Dibea F20Plus เพื่อทำความสะอาด' : f20_brush_cleaning.md
    - Smart 2:
        - 'วิธีเชื่อมต่อ Smart 2 เพื่อสั่งงานผ่านโทรศัพท์มือถือ' : smart2_app_con.md
    - Smart 3:
        - 'วิธีเชื่อมต่อ Smart 3 เพื่อสั่งงานผ่านโทรศัพท์มือถือ' : smart3_app_con.md
theme: readthedocs